### PR TITLE
Semantics with Vietnamese

### PR DESCRIPTION
**Pull request by nploi**
Hi team,
I want support Vietnamese language for this package, please review it.
Thank you.

### CODE REVIEW

**Comment by nploi** [comment]
hi @AlexV525, please help me review this too, i will add record with talkback late 😁

**Comment by nploi** [comment]
Hi @AlexV525, i added talkback record, please help me review this PR. Thank you.

https://user-images.githubusercontent.com/34020090/235417881-71345be3-685f-407c-be6d-49ac6ea72cfc.mp4

**Comment by nploi** [comment]
```
 info - lib/src/states/camera_picker_viewer_state.dart:274:34 - 'bodyText1' is deprecated and shouldn't be used. Use bodyLarge instead. This feature was deprecated after v3.1.0-0.0.pre. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

let me fix this @AlexV525 .

**Comment by AlexV525** [comment]
> let me fix this @AlexV525 .

You don't need to. I'll update them later.

**Review by AlexV525 — APPROVED** [review]
LGTM

**Comment by AlexV525** [comment]
@all-contributors Add @nploi for translation.

**Pull request merged**
